apiVersion: schemas.schemahero.io/v1alpha4
kind: Table
metadata:
  name: todos
spec:
  database: {{ .Values.psql.name }}
  name: todos
  schema:
    postgres:

      primaryKey:
      - id

      indexes:
        - columns: 
          - address
          isUnique: false

      columns:

      # pk id for individual record.
      - name: id
        type: uuid
        constraints:
          notNull: true

      # User's public Address
      - name: address
        type: text
        constraints:
          notNull: true
      
      - name: todo
        type: text
        constraints:
          notNull: true

      - name: completed
        type: boolean
        constraints:
          notNull: true
      
      - name: completedAt
        type: timestamp

      - name: createdAt
        type: timestamp
        constraints:
          notNull: true
